### ISSUE TITLE
Fatal error: Call to a member function getTitle() on null

### ISSUE THREAD

**Issue by tanc** [localgovdrupal/localgov_guides#28]
On the following guide page I'm seeing a fatal error: https://beta.lambeth.gov.uk/join-housing-register

I'm not sure what causes it but the fix appears to be to use `getEntity()` rather than rely on the magic method to fetch the entity. No idea why without digging through loads of code.

A bit of stack trace:

```
Error: Call to a member function getTitle() on null in Drupal\localgov_guides\EventSubscriber\PageHeaderSubscriber->setPageHeader() (line 34 of /var/www/lambethlocalgov/web/modules/contrib/localgov_guides/src/EventSubscriber/PageHeaderSubscriber.php)

#0 [internal function]: Drupal\localgov_guides\EventSubscriber\PageHeaderSubscriber->setPageHeader(Object(Drupal\localgov_core\Event\PageHeaderDisplayEvent), 'localgov_core.p...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#1 /var/www/lambethlocalgov/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Drupal\localgov_core\Event\PageHeaderDisplayEvent), 'localgov_core.p...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#2 /var/www/lambethlocalgov/web/modules/contrib/localgov_core/src/Plugin/Block/PageHeaderBlock.php(127): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('localgov_core.p...', Object(Drupal\localgov_core\Event\PageHeaderDisplayEvent))
#3 /var/www/lambethlocalgov/web/modules/contrib/localgov_core/src/Plugin/Block/PageHeaderBlock.php(97): Drupal\localgov_core\Plugin\Block\PageHeaderBlock->__construct(Array, 'localgov_page_h...', Array, Object(Drupal\Core\Routing\CurrentRouteMatch), Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher), Object(Symfony\Component\HttpFoundation\RequestStack), Object(Drupal\Core\Controller\TitleResolver))
```

**Comment by andybroomfield** [comment]
Just a quick check, is this happening because you deleted the guide parent?

**Comment by tanc** [comment]
hi Andy. It's possible. Sorry I don't have more info, it's all part of a hurried build process so I'm not 100% sure what caused it. If I get a moment I'll try and replicate.

**Comment by andybroomfield** [comment]
Ok @tanc I was able to cause the issue by creating a guide overview, then a guide page and then deleting the guide overview (parent page). I suspect thats what caused the issue, though it is a case we should handle, which your PR does however it will also need a test to show this is working.
